name: agristack
description: "Aplikacja mobilna do diagnostyki chorób roślin uprawnych z użyciem AI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  logger: ^2.6.2
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^12.0.1
  image: ^4.5.4
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.4.11
  isar_generator: 3.1.0+1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/static/
    - assets/models/
    - assets/images/
    - assets/images/guide/Pszenica/
    - assets/images/guide/Rzepak/
    - assets/images/guide/Ziemniak/
    - assets/images/guide/Pomidor/
